### ISSUE TITLE
Gem doesn't seem to work with TruffleRuby

### ISSUE THREAD

**Issue by mtortonesi** [ioquatix/bake-modernize#6]
When trying to launch:

<pre>bundle exec bake modernize</pre>

under truffleruby+graalvm-23.0.0 (installed from rbenv+ruby-build on an M1 MacBookPro), I get the following trace:

<pre>
bundler: failed to load command: bake (/Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/bin/bake)
define.c:75:in `rb_define_singleton_method': Message not supported. (Polyglot::ForeignException)
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/markly-0.9.0/ext/markly/markly.c:1152:in `Init_markly'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/markly-0.9.0/lib/markly.rb:11:in `<unknown>'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/markly-0.9.0/lib/markly.rb:11:in `Kernel#gem_original_require'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/markly-0.9.0/lib/markly.rb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `Kernel#gem_original_require'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize/actions.rb:8:in `load'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/scope.rb:36:in `Bake::Scope.load'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/loader.rb:61:in `Bake::Loader#scope_for'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:178:in `block in Bake::Context#base_for'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/loaders.rb:66:in `Array#each'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/loaders.rb:66:in `Bake::Loaders#each'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:177:in `Bake::Context#base_for'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:168:in `Bake::Context#instance_for'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:86:in `block in Bake::Context#initialize'
	from <internal:core> core/hash.rb:186:in `Hash#default'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:154:in `Hash#[]'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:154:in `Bake::Context#recipe_for'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:100:in `block in Bake::Context#initialize'
	from <internal:core> core/hash.rb:186:in `Hash#default'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:120:in `Hash#[]'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:120:in `Bake::Context#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/base.rb:74:in `Bake::Base#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize.rb:7:in `#<Module:0x3a38>#modernize'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/recipe.rb:130:in `Bake::Recipe#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:122:in `Bake::Context#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command/call.rb:50:in `Bake::Command::Call#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command/top.rb:78:in `Bake::Command::Top#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/samovar-2.2.0/lib/samovar/command.rb:21:in `Samovar::Command.call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command.rb:29:in `Bake::Command.call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/bin/bake:29:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/bin/bake:25:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli/exec.rb:58:in `Bundler::Exec#kernel_load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli/exec.rb:23:in `Bundler::Exec#run'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:486:in `Bundler::CLI#exec'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/command.rb:27:in `Thor::Command#run'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/invocation.rb:127:in `Thor::Invocation#invoke_command'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor.rb:392:in `Thor.dispatch'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:31:in `Bundler::CLI.dispatch'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/base.rb:485:in `Thor::Base::ClassMethods#start'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:25:in `Bundler::CLI.start'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/gems/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/friendly_errors.rb:120:in `Bundler.with_friendly_errors'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/gems/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/bin/bundle:44:in `<main>'
</pre>

Not sure what's going on here, because rb_define_singleton_method should be working on TruffleRuby. Any hints?

**Comment by ioquatix** [comment]
It looks like a problem with `markly` which is an AST/processor/generator for Markdown. I don't know why it's not working. It's a moderately complex native extension. cc @eregon this is probably low priority but if you have a moment?

**Comment by eregon** [comment]
Could you report an issue at https://github.com/oracle/truffleruby/issues? I do not have time to look right now and anyway that's much better to track it.

**Comment by ioquatix** [comment]
@mtortonesi do you mind following up if you have time? I'm completely swamped right now.

**Comment by mtortonesi** [comment]
I just did:

https://github.com/oracle/truffleruby/issues/3207

**Comment by ioquatix** [comment]
Probably rewrite your issue above to be specifically about `markly`.

**Comment by ioquatix** [comment]
I've released `v0.9.1` of markly which should fix the issue.

**Comment by mtortonesi** [comment]
I can confirm that:

<pre>
bundle update markly
</pre>

fixed the issue above.

I hate to report it, but another related issue came up:

<pre>
bundler: failed to load command: bake (/Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/bin/bake)
/Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/util/hash/sha1dc/sha1.c:383:in `sha1_compression_states': missing LLVM builtin: llvm.fshl.v2i32 (Polyglot::ForeignException)
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/util/hash/sha1dc/sha1.c:1713:in `sha1_process'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/util/hash/sha1dc/sha1.c:1819:in `SHA1DCUpdate'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/util/hash/collisiondetect.c:32:in `git_hash_sha1_update'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/util/hash.c:98:in `git_hash_buf'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/config_file.c:864:in `config_file_read'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/config_file.c:101:in `config_file_open'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/config.c:310:in `git_config_add_backend'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/config.c:100:in `git_config_add_file_ondisk'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/repository.c:1190:in `load_config'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/repository.c:1258:in `git_repository_config__weakptr'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/repository.c:772:in `obtain_config_and_set_oid_type'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/repository.c:1046:in `git_repository_open_ext'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/vendor/libgit2/src/libgit2/repository.c:1126:in `git_repository_open'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rugged-1.6.3/ext/rugged/rugged_repo.c:1623:in `rb_git_repo_discover'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `Rugged::Repository.discover'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize/actions.rb:55:in `#<Module:0x4588>#repository_url'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize/actions.rb:30:in `#<Module:0x4588>#update'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize/actions.rb:12:in `#<Module:0x4588>#actions'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/recipe.rb:130:in `Bake::Recipe#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:122:in `Bake::Context#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/base.rb:74:in `Bake::Base#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-modernize-0.17.8/bake/modernize.rb:7:in `#<Module:0x3c78>#modernize'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/recipe.rb:130:in `Bake::Recipe#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/context.rb:122:in `Bake::Context#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command/call.rb:50:in `Bake::Command::Call#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command/top.rb:78:in `Bake::Command::Top#call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/samovar-2.2.0/lib/samovar/command.rb:21:in `Samovar::Command.call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/lib/bake/command.rb:29:in `Bake::Command.call'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/bake-0.18.2/bin/bake:29:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/bin/bake:25:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli/exec.rb:58:in `Bundler::Exec#kernel_load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli/exec.rb:23:in `Bundler::Exec#run'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:486:in `Bundler::CLI#exec'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/command.rb:27:in `Thor::Command#run'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/invocation.rb:127:in `Thor::Invocation#invoke_command'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor.rb:392:in `Thor.dispatch'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:31:in `Bundler::CLI.dispatch'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/vendor/thor/lib/thor/base.rb:485:in `Thor::Base::ClassMethods#start'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/cli.rb:25:in `Bundler::CLI.start'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/gems/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/mri/bundler/friendly_errors.rb:120:in `Bundler.with_friendly_errors'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/gems/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
	from <internal:core> core/kernel.rb:381:in `Kernel#load'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/bin/bundle:44:in `<main>'
</pre>

**Comment by ioquatix** [comment]
It's okay to report issues :)

**Comment by mtortonesi** [comment]
By upgrading to truffleruby+graalvm-dev and adding the [3.2 coverage update patch](https://github.com/oracle/truffleruby/pull/3151), I managed to fix the `missing LLVM builtin: llvm.fshl.v2i32` problem above. Great!

I am getting a new issue, though:

```
bundle exec bake modernize
 1.33s    error: Bake::Command [ec=0x56f8] [pid=67599] [2023-08-11 15:33:32 +0200]
               |   NoMethodError: undefined method `set_scheduler' for Fiber:Class
               |   → vendor/bundle/truffleruby/3.1.3.9/gems/async-2.6.3/lib/async/reactor.rb:21 in `initialize'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/async-2.6.3/lib/kernel/sync.rb:23 in `Sync'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-modernize-0.17.8/bake/modernize/gemspec.rb:178 in `valid_uri?'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-modernize-0.17.8/bake/modernize/gemspec.rb:195 in `detect_funding_uri'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-modernize-0.17.8/bake/modernize/gemspec.rb:32 in `update'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-modernize-0.17.8/bake/modernize/gemspec.rb:11 in `gemspec'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/recipe.rb:130 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/context.rb:122 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/base.rb:74 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-modernize-0.17.8/bake/modernize.rb:7 in `modernize'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/recipe.rb:130 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/context.rb:122 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/command/call.rb:50 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/command/top.rb:78 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/samovar-2.2.0/lib/samovar/command.rb:21 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/lib/bake/command.rb:29 in `call'
               |     vendor/bundle/truffleruby/3.1.3.9/gems/bake-0.18.2/bin/bake:29 in `<top (required)>'
               |     vendor/bundle/truffleruby/3.1.3.9/bin/bake:25 in `<top (required)>'
               |     /Users/mauro/.rbenv/versions/truffleruby+graalvm-dev/graalvm/Content
```

Perhaps I am missing some fiber scheduler related gem?

**Comment by eregon** [comment]
> Perhaps I am missing some fiber scheduler related gem?

TruffleRuby doesn't implement the Fiber scheduler yet (there is WIP about it on some branches, not really a priority while Truffle is not compatible with Loom).

**Comment by ioquatix** [comment]
As the issues that relate to this code base are essentially fixed, I am going to close this issue.
